name: Workflow A

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - .github/workflows/a.yaml

    pull_request: 
        branches: [main]
        paths:
            - .github/workflows/a.yaml
    

jobs:
    foo:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              working-directory: .
              run: |
                sleep 30
                echo "Hello World"
              