name: Workflow B

on:
    workflow_dispatch: 
    push:
        branches: [main]
        paths:
            - .github/workflows/b.yaml

    pull_request: 
        branches: [main]
        paths:
            - .github/workflows/b.yaml

    workflow_run:
        workflows: ["Workflow A"]
        types:
            - completed


jobs:
    foo:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              working-directory: .
              run: |
                sleep 3
                echo "Hello World"
